### ISSUE TITLE
Doesnt work anymore on Android Pie 9

### ISSUE THREAD

**Issue by moliata** [VREMSoftwareDevelopment/WiFiAnalyzer#201]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Comment by VREMSoftwareDevelopment** [comment]
@moliata 
In order to investigate the issue you are trying to report, please provide missing information in the above template.

**Comment by mborsetti** [comment]
**Describe the bug**
A "no data" dialog comes up and there's no data about Wi-Fi networks when running the app in Android 9 (Pie)

**To Reproduce**
Steps to reproduce the behavior:

1. Install the current version of Android OS (see https://www.android.com/versions/pie-9-0/)
2. Run the app
3. Notice how it doesn't do what it's supposed to do (see attachment)

**Expected behavior**
To work

**Screenshots**
![image](https://user-images.githubusercontent.com/26698111/43806284-e31d4f1e-9ad5-11e8-9000-57bba5f5f9c5.png)

Note
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

Additional context
Add any other context about the problem here.

**Comment by VREMSoftwareDevelopment** [comment]
@mborsetti 
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Comment by Jon8RFC** [comment]
I'm suffering from the same situation.  Screenshot and information above also apply to me.  The app worked fine on last month's Android release of 8.1.0.

Here are screenshots of my software info on my Google Play Store Pixel XL:
![pixel_xl_android_9](https://user-images.githubusercontent.com/12204953/43812257-ff6f7750-9a85-11e8-809b-a60f34375c21.png)
![pixel_xl_android_9_wifianalyzer](https://user-images.githubusercontent.com/12204953/43812258-ff7e75a2-9a85-11e8-97d2-6f88ef627da9.png)

**Comment by mborsetti** [comment]
@VREMSoftwareDevelopment

Same as @Jon8RFC:

![image](https://user-images.githubusercontent.com/26698111/43814191-a0b16d24-9afb-11e8-85a7-3d6817625812.png)


![image](https://user-images.githubusercontent.com/26698111/43814188-98a841fc-9afb-11e8-9aa2-40b84698676d.png)

**Comment by moliata** [comment]
I downloaded the sources and modified the code slightly. Adding ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission fixes the issue.

**Comment by moliata** [comment]
The only problem that still persists is that APs don't refresh only twice: when they show up and a single time afterwards.

**Comment by moliata** [comment]
Per further analysis, it seems that Android Pie introduced Wi-Fi Scanning restrictions, which limit 4 scans per 2-minute period in a foreground app.

**Comment by Jon8RFC** [comment]
Good find. That's a bummer, but I understand their reasoning for battery life.
https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-restrictions

I'm certainly no expert, and I couldn't easily find information, but wouldn't root permission be able to circumvent this new restriction?

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate #188, #199

**Comment by VREMSoftwareDevelopment** [comment]
@moliata Please try the BETA version of the application in Google Play Store.

**Comment by moliata** [comment]
Nope, restrictions regarding scanning interval doesn't work. Networks stay the same for 2 minutes before updating. Even though I walk 100 meters.

**Comment by VREMSoftwareDevelopment** [comment]
@moliata 
Reference #199 
Until Google fixes the "WifiManager startScan throttled in Android P" issues, the application will not work properly on Android P.

**Comment by Jon8RFC** [comment]
This looks like an option to at least improve the functionality:
https://issuetracker.google.com/issues/79906367#comment14

Limit WifiManager.startScan to once every 30 seconds, continually add to the list of devices found, rather than purging it regularly, and run WifiRttManager.startRanging at the shorter intervals.

This can make for a large list, and that's where user input would be helpful for how to manage it.  Here are some quick ideas:

1. Set the list to have an upper limit, and it's up to the user how large that list is; it's never erased unless manually purged.  The list is updated with WifiManager.startScan every 30 seconds, WifiRttManager.startRanging is the new regular activity.
2. Set the list to purge/overwrite upon each start up of the application and each WifiManager.startScan (current behavior, it seems).
3. Allow multiple lists, with upper limits, which are based upon GPS locations within certain ranges (20m?); GPS is acquired, then list for that location is loaded and updated with WifiManager.startScan every 30 seconds, with WifiRttManager.startRanging running regularly.
4. Same as 3, but with logic to to prioritize the "recently found" devices first on the last WifiRttManager.startRanging, then run through the list of the devices which didn't respond on the last WifiRttManager.startRanging activity.

Number 4 could be useful for large lists, as it seems like only 20 devices within range can start to make scans take a little longer.  However, the WifiRttManager.startRanging may be more effective with time usage than full scans with WifiManager.startScan.

**Comment by VREMSoftwareDevelopment** [comment]
@Jon8RFC Great ideas, can you please create a pull request?

**Comment by Jon8RFC** [comment]
I would if I could.  I'm not smart enough to be a programmer, unfortunately, otherwise I'd pound it out in a few hours myself.

When I said "user input would be helpful for how to manage it", I meant more of a general discussion for  people to post their ideas and rip apart mine for feasibility.  Then, hopefully, someone with time/smarts can write up some new code.

I'm sure you're pretty busy, so it's just a back burner idea if it wasn't something you'd considered before.  I appreciate the time and effort you've already put into this app!  I'm no where near smart enough to do something like this myself.

**Comment by wesinator** [comment]
Still not working version 2.0.4

Nokia 5 Android 9
![Android 9 stuck on Scanning](https://user-images.githubusercontent.com/5124946/56577568-4e536280-6599-11e9-8785-e1dfa37eecd8.png)

The app is stuck on scanning. Location permission is granted

**Comment by VREMSoftwareDevelopment** [comment]
@wesinator 

We do not have your specific device, so we can not reproduce your specific issue. 

Bases on other devices and behaviors running Android 9+, here are a few steps/suggestions :
1) Install the latest version of the Application (version 2.0.4).
2) Location Services on the Device must be enable and functioning.
3) Application must have access to Location Services
4) Allow at least 2 to 3 minutes for the first scan results

Reference documentation: [Location Service Permission Requirements](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Location-Service-Permission-Requirements)
(Specific sections: Permissions and Throttling)

Regards,

VREM Development Team
