### ISSUE TITLE
Add fallback to use CHANGE_WIFI_STATE permission if geolocation not allowed on Android 8

### ISSUE THREAD

**Issue by Nik-mmzd** [VREMSoftwareDevelopment/WiFiAnalyzer#217]
**Please search issues (open and closed) to see the issues has already been reported.**

**Is your feature request related to a problem? Please describe.**
Latest update in Google Play (2.0.2) makes this app hard to use with Android 8 (at least): you need to grant geolocation permission, enable geolocation, change geolocation from "gps only"...

**Describe the solution you'd like**
Can you use CHANGE_WIFI_STATE permission to scan WiFi as fallback if no geolocation permissions granted instead of closing the app?
I ask this question because all worked perfectly without geolocation before 2.0.2

**Describe alternatives you've considered**

**How I can help**
A clear and concise description of what you can do to help.

**Additional context**

Device: SM-N960F, Android 8.1.0

**Comment by VREMSoftwareDevelopment** [comment]
@Nik-mmzd 
Please fill the missing information in the feature request template above.

Have you considered just download [1.9.3 apk](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/releases/tag/V1.9.3-F-DROID) directly and installing it?
There are new play store requirements that are forced on developers to comply to more strict Android deployments. We did investigate different alternatives and sorry to say did not find any good solution so far. Do you have any sample code, links or documentation for the proposed solution, that would be very helpful.

Regards,

VREM Development Team

**Comment by Nik-mmzd** [comment]
Yep, downloading 1.9.3 and disabling auto-updates is also a solution.

> There are new play store requirements that are forced on developers to comply to more strict Android deployments
Ok, thanks for explanation, I think it's enough to close this issue

> Do you have any sample code
Sorry, but I'm not Android dev, I just read your FAQ and linked Android documentation...

**Comment by silversparrow** [comment]
but what if i downloaded the app from fdroid??????????
you use the same version.....

"There are new play store requirements that are forced on developers to comply to more strict Android deployments"

fdroid is not google play....thank god.

i will not enable location as long as the google play reason is the only one.

**Comment by Nik-mmzd** [comment]
App has no way to send location data, as I see, so I think it's safe. Or you can use older version like me :Ъ

**Comment by VREMSoftwareDevelopment** [comment]
@silversparrow 

Android OS 9 Wi-Fi scanning permissions requires ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION (#202). This is not our requirement, this is Google Android requirement since OS 6 ([Location Permission](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-OS-6---Location-Service-ON)).

As we stated above, so far we did not find a solution to include different permission requirements based on the Android OS Version. In order to support Android OS 9 we need to add location permission, any new application builds/releases will use this permission and will apply to all (Google Play Store and/or F-Droid).

Previously we have build the application only up-to Version OS 5.1, this trick worked so far, starting November 2018  this will not work anymore. There are new play store requirements that are forced on developers to comply to more strict Android deployments. [Meet Google Play's target API level requirement](https://developer.android.com/distribute/best-practices/develop/target-sdk)
