### ISSUE TITLE
Option to choose the application language - 2x Polish language

### ISSUE THREAD

**Issue by olekstomek** [VREMSoftwareDevelopment/WiFiAnalyzer#258]
I see Polish on the language selection list twice ("Polski" and "Polski (Polska)"). I didn't notice the difference between these two options.
App version: 2.0.8. - 49GS(9-28)
![Screenshot_2019-08-31-21-25-45-466_com vrem wifianalyzer](https://user-images.githubusercontent.com/26818304/64080649-e0613980-ccf6-11e9-9355-bafec44916c2.png)

**Comment by VREMSoftwareDevelopment** [comment]
@olekstomek 

- "Polski (Polska)" is Android OS language configuration
- "Polski" is application language configuration

Switch Android OS to English and you will see two English selections.
This feature allows the user to use Android OS language, instead of the using application language selection.
