### ISSUE TITLE
Scanning WIFI takes too long during cold start (Android 9)

### ISSUE THREAD

**Issue by 18771052572** [VREMSoftwareDevelopment/WiFiAnalyzer#269]
[How to report a bug](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Feedback)

**Please search issues (open and closed) to see the issues has already been reported.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Note**
Some behaviour only occurs on certain devices or versions of Android, please provide the following screenshots/information Device/Android OS (Settings → About Phone) and WiFi Analyzer version (Menu -> About)

**Additional context**

**Provide Device/Android OS information**

Phone Model: Honor V9
APP Version：2.1.1

**Comment by VREMSoftwareDevelopment** [comment]
@18771052572 
Please fill the missing information in the request template we have provided above, this helps us to investigate and resolve the issue faster.

**Comment by 18771052572** [comment]
Sorry, no detailed description last time

**Comment by 18771052572** [comment]
Steps to reproduce
1. Install the app and start the app
2. Press the menu key to destroy the app process
3.Reopen the app

Expectation: Quickly display WiFi list
Actual: Always showing Scanning (for example: attachment picture)
Android Version:9.1.0

This is a question of probability
![Screenshot_20191204_134408_com vrem wifianalyzer](https://user-images.githubusercontent.com/46990154/70415043-b4dcb080-1a96-11ea-8ee0-5c3aa6e5cbad.jpg)

**Comment by Jon8RFC** [comment]
I recall seeing that problem on Android 9 due to the wifi scan throttling.  Could that be related?  Once wifi analyzer got a successful scan, it wouldn't fail like that, but it also won't update either.  So it only _seemed_ like it was working.

If you open up Android wifi settings in split screen mode, does scanning resume when the wifi settings screen updates/scans?
https://www.youtube.com/watch?v=6XLRUwdI2uY

That would likely be a method to see if it's the Android 9 wifi scan throttling rather than the app.

**Comment by VREMSoftwareDevelopment** [comment]
@18771052572 as @Jon8RFC mentioned above the problem you are seeing is related to Android 9 Wi-Fi scan throttling.

Please take a look at [FAQ](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#faq), specifically Android Pie throttling Wi-Fi scanning section
