### ISSUE TITLE
"Unfortunately,  WiFiAnalyzer has stopped" after pressing "PortAuthority" item in menu on Android modified and hardened for security and privacy without Google services like Google Play

### ISSUE THREAD

**Issue by Anonymous123456789012** [VREMSoftwareDevelopment/WiFiAnalyzer#282]
Good day

Firstly, again, I want to thank you very much for creating "WiFiAnalyzer"!
It's awesome software!

In WiFiAnalyzer 2.1.1 and older WiFiAnalyzer 2.0.8, "PortAuthority" item was added to menu.
When I'm pressing "PortAuthority" item on Android modified and hardened for security and privacy without Google services like Google Play, WiFiAnalyzer will stop.

STR:
1. Use Android modified and hardened for security and privacy without Google services like Google Play
2. Press "PortAuthority"

and enjoy "Unfortunately,  WiFiAnalyzer has stopped"

I'm using WiFiAnalyzer 2.1.1 on Android 6.0.1 (modified and hardened for security and privacy, so no Google services like Google Play are installed there) on Sony Xperia Z3 Compact.

It works fine with WiFiAnalyzer 2.1.1 on stock non modified Android 6.0.1 on LG Spirit.

Best regards

**Comment by VREMSoftwareDevelopment** [comment]
We are not able to reproduce the issue that you are reporting, since we do not have a your specific device.

Here are a few possible solution to your specific issue:
- provide us with logs when application stops
- install alternative application store, such as F-Droid
- install [Port Authority](https://github.com/aaronjwood/PortAuthority)

Please use provided templates to report issues and do not forget to fill all questions/topics in the templates.

**Comment by VREMSoftwareDevelopment** [comment]
Possible fix will be available in next release.

**Comment by Anonymous123456789012** [comment]
Point is that I don't have Port Authority installed, same as Google services like Google Play/Shop.
Thank you very much!
I'm confirming that issue is fixed in WiFiAnalyzer 2.1.2, as pressing "PortAuthority" item in menu, doesn't anymore crashing WiFiAnalyzer, no it doesn't do anything, per probably not having Google services like Google Play/Shop installed.
Thank you very much one more time!
