### ISSUE TITLE
Set up automatic update on F-Droid

### ISSUE THREAD

**Issue by jtotht** [VREMSoftwareDevelopment/WiFiAnalyzer#291]
**Is your feature request related to a problem? Please describe.**
Version 2.1.2 is out since five days, but it’s still not on F-Droid.

**Describe the solution you'd like**
I think it’s a perfect time to set up automatic update of the app on F-Droid. As far as I understand the [documentation](https://f-droid.org/en/docs/Build_Metadata_Reference/#AutoUpdateMode), it’s just replacing `AutoUpdateMode: None` with `AutoUpdateMode: Version V%v-F-DROID` in the [metadata file](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.vrem.wifianalyzer.yml).

**Describe alternatives you've considered**
Still update manually. This is easier in the short run, but much more costly in the long run.

**How I can help**
I can create a pull request in F-Droid’s GitLab repo, but I don’t want to do so without the app author’s consent.

**Comment by VREMSoftwareDevelopment** [comment]
F-Droid merge request was submitted at the same time as GitHub release.

[Update WiFiAnalyzer to version 2.1.2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6548)

The issue is not manual or automatic update, but rather F-Droid publish timeline.

You are welcome to change the metadata file. 
Please make sure that change to metadata file will work.

Regards,
VREM Development team
