### ISSUE TITLE
Feature request - Utilize Wifi RTT for rangefinding by default in Android 9+

### ISSUE THREAD

**Issue by timothycpr** [VREMSoftwareDevelopment/WiFiAnalyzer#307]
Looking at results from the current app, it appears AP signal values are still used to estimate distance under Android 10. Shielding my phone to reduce the received signal from my WAP causes the distance estimate to vary proportionately. This was checked with the current version of the app running under Android 10 on a Pixel 3a XL. 

I saw it mentioned previously that stating in Android 9 Wifi RTT was added to the Android public API, but didn't see any note about it being utilized, but I do see that the export notes if a device supports 802.11mc.

The feature request is to use that Wifi RTT API for ranging (or offer it a selectable option) and fall back to the signal-based estimate where that is not available. It seems that many APs support it but do not advertise it in their beacon frames:

http://people.csail.mit.edu/bkph/ftmrtt_aps

Keep up the great work.

**Comment by timothycpr** [comment]
If it turns out this is just a documentation issue and the problem is on my device, feel free to close.

**Comment by VREMSoftwareDevelopment** [comment]
@timothycpr 

Yes you are correct, **"AP signal values are still used to estimate distance"**. 

We will not have an opportunity to implement this feature in the near future, since all current contributors are busy with other work.

When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project and become a contributor. It would be great to add new contributors to this project.
