### ISSUE TITLE
v3.0.2 can't load APs, or super slow load

### ISSUE THREAD

**Issue by muchqs** [VREMSoftwareDevelopment/WiFiAnalyzer#320]
I upgraded to v3.0.2 on F-Droid, and experiencing very slow loading of access points, sometimes it doesn't load anything at all and just shows a blank screen. Uninstalled and reinstalled clean and still the same thing. Downgraded to v3.0.1 and AP list loads almost instantly.

Upon starting v3.0.2, one of the following three scenarios will occur on my phone:

scenario 1:
The top of the screen shows the 5ghz wifi I'm connected to, but the AP list does not load at all. It's just empty screen even after waiting 10+ seconds.

scenario 2:
Entire screen is empty. No AP list, top of the screen does not show the AP I'm connected to. Wait 10+ seconds, suddenly the AP list loads and the top shows AP I'm connected to.

scenario 3:
AP list loads, slowly. But the top does not show the 5ghz AP I'm connected to, it also does not show in the AP list, in fact, it seems all the 5ghz APs do not show in the list even though it is checked to show in options.

After downgrading to v3.0.1, everything works and loads fast.

Also a separate problem, it shows my 2.4ghz wifi has WPS on. But it is disabled in router.

My phone is Huawei P20 Pro CLT-L04 running Android v9.1
Router is an ASUS Blue Cave.

**Comment by VREMSoftwareDevelopment** [comment]
@muchqs 
Very strange! 
Will investigate.

**Comment by VREMSoftwareDevelopment** [comment]
The only major difference between 3.0.1 and 3.0.2 is support for different version of Android OS (Android API's do change between versions.).

- 3.0.1 supports Android 10 
- 3.0.2 supports Android 11

There is no issues while testing on the other devices available.
Probably the issue is Huawei P20 Android 9, [Android 9 Wi-Fi throttling](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/wiki/Android-WiFi-scanning-throttling) and application Android 11 API support.

Recommendation, do not upgrade application to version 3.0.2, until Huawei P20 is upgrades to at least Android 10.
