### ISSUE TITLE
Feature request: filter networks by OUI/BSSID

### ISSUE THREAD

**Issue by drygdryg** [VREMSoftwareDevelopment/WiFiAnalyzer#334]
I would like to be able to filter networks by BSSID, OUI, or by part of BSSID from the filter popup.
OUI is the first 3 bytes of the BSSID. For example, for the BSSID `11:22:33:44:55:66` the OUI is `11:22:33`.
OUI `11:22:33` will match to:
`11:22:33:44:55:66`
`11:22:33:AB:cd:ef`
`11:22:33:66:55:44`
etc.
Part of MAC address `11:22:33:44:5` will match to:
`11:22:33:44:55:66`
`11:22:33:44:5A:BC`
etc.
And `11:22:33:44:55:66` will exact match to `11:22:33:44:55:66`.

It would also be nice to add the ability to enter BSSID as a regexp. We can use `%` as a substitute character.
For example, `%%:%%:33:44:55:66` will match to:
`11:22:33:44:55:66`
`ab:cd:33:44:55:66`
`1A:8C:33:44:55:66`
etc.

**Comment by VREMSoftwareDevelopment** [comment]
Interesting idea, unfortunately we will not have an opportunity to implement this feature in the near future, since all current contributors are busy with other work.

When we don't have an opportunity or time to implement a feature, we encourage developers to fork the project, create PR and become a contributor. 

It would be great to add new contributors to this project.
