### ISSUE TITLE
F.R.: Display Country Code

### ISSUE THREAD

**Issue by pseudodamaging** [VREMSoftwareDevelopment/WiFiAnalyzer#65]
Feature Request:
Display Country Code from the beacons of the APs in the Access Points View.
This would help to spot incorrectly configured Wireless Routers.

**Comment by VREMSoftwareDevelopment** [comment]
Currently there is no available Android API to request country code from the Access Point.

**Comment by Doliman100** [comment]
I suggest reopening this issue, because the country code can now be accessed using the `ScanResult.getInformationElements()` function, which was added in API level 30. I personally was looking for this feature to check what countries the LAR system of my Intel AX210 module sees nearby. But later I switched to using the `lswifi --country` tool, running directly on my desktop where the module is installed.
Take note that sometimes country codes are not written in standard alpha2 format. I met "#a" country code which appears to be a special Broadcom code. According to the 802.11-2024 standard the country code "XX" is also valid and using for noncountry entity, but I didn't meet it. I think it's enough to just check if the first two characters are printable (in range 0x20-0x7E).
The CommView software displays it as is, for example "Code: #a", "Code: GB" and "Code: XX". It also displays the 3rd character as "Environment: Any (0x20)". According to the `dot11CountryString` description, the valid values are 0x20, 0x49, 0x4F, 0x58 and 0x01-0x06. If it is in range 0x01-0x06, for example the value 0x04, which refers to Table E-4, displays as "Environment: 4". If the value is out of range, it displays "Environment: Unknown (0x7)". I met only the 0x20 and 0x04 values and I don't know what it is used for, so I'm not sure if we need it. The Linux hostapd prints it as "country_code=GB\ncountry3=0x4"
You need to loop through all `ScanResult.getInformationElements()` and find the one with `InformationElement.getId() == 7 (WLAN_EID_COUNTRY)`. Then access the first two bytes from `InformationElement.getBytes()` which are the country, and optionally the third one which is the environment.

This function also can be used to export the raw `.ies` data for further analysis. Here is a Kotlin snippet which walks through the list and serializes it to the standard beacon frame format compatible with existing analysis tools, such as https://github.com/joshschmelzle/lswifi: `lswifi -decoderaw AndroidWifi.ies`. It also can be converted to `.pcapng` file format and analyzed using Wireshark or CommView.
```kotlin
val results = wifiManager.scanResults
var iesBuffer = ByteBuffer.allocateDirect(1024)
for (result in results) {
    val elements = result.informationElements
    iesBuffer.rewind()
    for (element in elements) {
        val ieBuffer = element.bytes
        val ieBufferSize = ieBuffer.remaining()

        // ieBufferSize + 3 is the max possible data size, including the header
        // resize if capacity is not enough
        if (iesBuffer.remaining() < ieBufferSize + 3) {
            // round up the data size to the closest multiple of 1024
            val tempBuffer = ByteBuffer.allocateDirect(iesBuffer.limit() + (ieBufferSize + 3 + 1023).and(1023.inv()))
            iesBuffer.flip()
            tempBuffer.put(iesBuffer)
            iesBuffer = tempBuffer
        }

        // write header
        iesBuffer.put(element.id.toByte())
        if (element.id == 255) {
            iesBuffer.put((ieBufferSize + 1).toByte())
            iesBuffer.put(element.idExt.toByte())
        } else if (element.idExt == 0) {
            iesBuffer.put(ieBufferSize.toByte())
        } else {
            throw RuntimeException("element.idExt != 0")
        }

        // write body
        iesBuffer.put(ieBuffer)
    }
    val iesStr = iesBuffer.array().toHexString(iesBuffer.arrayOffset(), iesBuffer.arrayOffset() + iesBuffer.position())
    Log.i("MainActivity", iesStr)
}
```
