### ISSUE TITLE
WiFiAnalyzer equivalent on iOS

### ISSUE THREAD

**Issue by sjallyn** [VREMSoftwareDevelopment/WiFiAnalyzer#69]
Please make an iOs version of this app.

**Comment by VREMSoftwareDevelopment** [comment]
Why there is no WiFi Analyzer on iOS?

[https://www.adriangranados.com/blog/where-did-wifi-analyzer-gol](https://www.adriangranados.com/blog/where-did-wifi-analyzer-go)

**Comment by sjallyn** [comment]
Thanks for the thorough explanation. I'm on iOs 10 and really don't want to jailbreak my phone. I loved the look and info provided by your app, but I will find some other way to get the info I need. 
If there is ever a way to work with Apple to make this work again, I'd happily. Buy your app. 

Stuart J. Allyn

**Comment by goetzc** [comment]
> Why there is no WiFi Analyzer on iOS?
> 
> [https://www.adriangranados.com/blog/where-did-wifi-analyzer-gol](https://www.adriangranados.com/blog/where-did-wifi-analyzer-go)

That link is now showing a status 404.

**Comment by daluu** [comment]
You can always try to find archive of broken/obsolete links/pages:

https://web.archive.org/web/20190529223900/https://www.adriangranados.com/blog/where-did-wifi-analyzer-go

a repost of the article in case link has issues later:

> WiFi Analyzer and other wifi scanner apps for the iPhone were removed from the App Store in March, 2010 due to the use of private frameworks. Private frameworks are libraries that cannot be used by third-party developers, as clearly stated in Apple's Developer Agreement. Unfortunately, some system resources can only be accessed using these frameworks, and the wifi card in the iPhone is one of them. To make things worse, starting in iOS 5, apps cannot access the wifi card even when using the private framework, so users who had the app installed and upgrade to iOS 5 will not longer be able to run the app. Well, the app will run but it will do nothing.

There are many reasons why these frameworks are kept private. One of them is to ensure that apps do not negatively affect the user experience, for example, by draining the battery. Other reason is to give Apple the freedom to change different aspects of the library until it reaches maturity so that it can be used by developers in a safe manner. With no access to these private frameworks for wifi scanning and with the restrictions of the sandbox environment in newer versions of iOS, the only option is to install and run the app in a "jailbreak" device.

> WiFi Analyzer is available in the [Cydia Store](https://web.archive.org/web/20190529223900/http://apt.thebigboss.org/onepackage.php?bundleid=com.agranados.wifianalyzer), but keep in mind that it only supports the 2.4 GHz band and has limited support for 802.11n networks. Also, it has not been tested in iOS 6 or higher. The app seems to work fine in iOS 5 and 6 with jailbreak.

> UPDATE #1: I've released a completely new version for iOS 7 called WiFi Explorer. This new version supports 2.4 GHz as well as 5 GHz networks, offers nicer graphs and more network details. Keep in mind that a jailbreak is still required and the app can only be found on Cydia. See official description [here](https://web.archive.org/web/20190529223900/http://moreinfo.thebigboss.org/moreinfo/depiction.php?file=wifiexplorerDp).

> UPDATE #2: WiFi Explorer for iOS 7 will not work on iOS 8. Not sure what changed in the latest version of iOS, but I hope a fix can be found in the next weeks.

> UPDATE #3: [WiFi Explorer for iOS](https://web.archive.org/web/20190529223900/http://www.adriangranados.com/apps/ios-wifi-explorer) now works on iOS 8. WiFi Analyzer will not longer be maintained.

**Comment by goetzc** [comment]
Thank you.
