### ISSUE TITLE
Add additional next/previous navigation

### ISSUE THREAD

**Issue by naoaustin** [VREMSoftwareDevelopment/WiFiAnalyzer#82]
Thank you for this great app. I appreciate If you can add swipe interface to switch list/graphs each.

Regards,
Nao

**Comment by VREMSoftwareDevelopment** [comment]
Hi Nao,

This is an interesting idea for a feature. Would you be able to elaborate in more detail on when and why you would use this option instead of navigation drawer?

The application is using [navigation drawer material design pattern](https://material.io/guidelines/patterns/navigation-drawer.html). Navigation Drawer is hidden and can be shown by swiping the screen from left edge to right or tapping the navigation drawer icon on the action bar.

Thank you,
The VREM Development Team

**Comment by naoaustin** [comment]
Thank you for your response. In addition to the navigation drawer, I thought it more convenient if I can switch the view by swipe between Access Points, Channel Rating, Channel Graph, and Time Graph, since I now need two touches to switch view.

Regards,
Nao

**Comment by VREMSoftwareDevelopment** [comment]
Navigation Drawer guaranties two touch events to be able to switch between any two views in the application.

Currently swipe action will require one, two, three or more touch events to switch between two views in the application. The first view and the order of views becomes important, since we want to minimize navigation touch events, a new user preference/configuration needs to be added "Views Orders" to the application.
 
Example, based on the current order of views:
- First view Access Points
- Access Points to Channel Rating: 1 swipe
- Access Points to Channel Graph: 2 swipe
- Access Points to Time Graph: 3 swipe
- and so on...

By any chance, do you have any knowledge in Android development? When we don't have an opportunity to implement a feature in the short term, we encourage developers to fork the project.

Thank you,
The VREM Development Team

**Comment by Gitoffthelawn** [comment]
Swiping left and right now working consistently for me. :(
