### ISSUE TITLE
Audible mode

### ISSUE THREAD

**Issue by joemck** [VREMSoftwareDevelopment/WiFiAnalyzer#93]
It would be useful if the user could select an access point to monitor, and it would beep at a rate depending on signal strength.

This way you could set your phone in the area you want to receive wifi, then go to the router in the other room and adjust it while hearing constant feedback on signal strength.

I think this would go nicest on a screen that shows a visualization of just that one AP's strength, since both are oriented toward surveying and adjusting strength of one signal.

**Comment by Simplenuity** [comment]
From the short time I have checked out WiFiAnalyzer in my search for an open source replacement this seems to be a main feature missing, a [Signal Meter](http://pichost.org/image/3BGl).

Otherwise great software!

**Comment by tupperdose** [comment]
I second the mentioned feature request by the OP. Though for my task I'd like a slightly different approach: I'd like to hear an audio notification as soon as wifi networks appear in a specified frequency range. So I'd like to specify what channels I'd like to monitor, and as soon as there is any (hidden) SSID is picked up my device, I'd like to hear an audio notification (beep, ring etc.).

Coming back to the original request: Pick a specific SSID to monitor and a form with that information (channels, SSID...) gets filled automatically. In my use case I wouldn't be able to pick any specific SSID because I'm just interested in any occuring SSID on a specific channel range. So I would fill out the said form manually with an asterisk in the SSID field and pick my channels of interest manually as well. The OP would now be hearing an audio tone that represents the signal strength. I'd hear an audio tone as soon as any wifi signal appears on my specified parameters.

**Comment by hackerb9** [comment]
I think a Geiger counter-like Signal Meter would be nice, with more frequent clicks as the meter goes higher so you don't have to look at the screen while adjusting antennas.

This app (also called "WiFi Analyzer", but written by someone in China) has that capability:

  http://a.farproc.com/wifi-analyzer

Note that his interface for selecting the SSID is terrible, mostly because he sorts them alphabetically instead of by signal strength. 

    Perhaps this should be split into a separate feature request, but I do like @Tupperdose's idea of having the meter be tuned to a specific channel instead of SSID. I think that actually might be more useful and interesting to me. 

If no access points are on a channel, I suggest the meter should drop very low, but not all the way to zero. Every channel has some baseline noise level and this meter should be able to show that. (Sometimes machinery and other electronics can make a channel unsuitable, but not show up on a standard WiFi analyzer.)

I don't know if the Android API allows you to read the raw noise level without reference to a specific SSID, but if so, one could use that as the value for the meter at all times. Besides being simple, I think this would satisfy tuperdose as well, since an active SSID on the channel would cause increased RF noise, and thus an audible alert as the Geiger counter starts clicking rapidly.
